# Generated by Django 6.0.4 on 2026-05-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_pedido_estado_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
